# -*- coding: utf-8 -*-
"""Airofit_Business_case.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/venkatesh-ux/Matplotlib-Seaborn/blob/main/Airofit_Business_case.ipynb
"""

# importing tha libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!gdown https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/001/125/original/aerofit_treadmill.csv?1639992749

#Reading the dataset

df = pd.read_csv('aerofit_treadmill.csv?1639992749')
df.head()

df.shape

"""We can see that shape of the Dataset is 180 Rows and Columns."""

print('Min: ',min(df['Usage'])),print('Max: ',max(df['Usage']))

"""The average number of times the customer plans to use the treadmill each week. Minimum days is 2 and max is 7"""

print('Max: ',min(df['Fitness'])),print('Max: ',max(df['Fitness']))

"""Self-rated fitness on a 1-to-5 scale, where 1 is the poor shape and 5 is the excellent shape."""

df.info()

df['Gender'] = df['Gender'].astype('category')

df['MaritalStatus'] = df['MaritalStatus'].astype('category')

df['MaritalStatus'].nunique()

df.info()

df.describe()

#df['Product'].value_counts()
df['MaritalStatus'].value_counts()
df['Gender'].value_counts()

"""From the above it is clear that **male** are the major using the treadmill."""

df['Product'].value_counts()

"""* The KP281 is an entry-level treadmill that sells for $1,500.

* The KP481 is for mid-level runners that sell for $1,750.

* The KP781 treadmill is having advanced features that sell for $2,500.

Compared to all the models people are using the entry-level treadmill then the other 2.
"""

# Plotting
plt.figure(figsize=(6, 4))
plt.scatter(df['Age'], df['Income'], color='blue', marker='o', label='Age vs Income')
plt.title('Scatter Plot of Age vs Income')
plt.xlabel('Age')
plt.ylabel('Income')
plt.legend()
plt.grid(True)
plt.show()

df['MaritalStatus'].value_counts()

sns.countplot(data=df,x='Gender',hue='Product')
plt.title('Sales of products by Gender')
plt.show()

"""We can see from the above plot that, both the genders are using the **entry-level** treadmill most and female is using the **medium-level** and also men. But female are using the **advanced features** one very little."""

sns.histplot(data=df,x='Income',hue='Product',kde=True)
plt.title('Trend of all the 3 product sales and the product buyer Income')
plt.show()

"""Also we can see people with **higher salary(>70000)** are tend to buy the **advanced-level** treadmill."""

sns.histplot(data=df,x='Age',hue='Product',kde=True)
plt.title('Trend of all the 3 product sales and the product buyer Age')
plt.show()

"""We can observe that people with age >20 and < 40 are spending the mony most on treadmill or fitness."""

sns.lineplot(x='Age',y='Income',hue='Product',data=df)
plt.show()

sns.boxplot(df,x='Income',y='MaritalStatus')
plt.show()

"""We can observe that there is a miner change in the mean salary of the single and the partnered people. It means signle people are tend ti have less age less experiance."""

plt.rcParams['figure.figsize'] = [4, 4]
sns.pairplot(df)
plt.show()

df.isnull().sum()

sns.boxplot(df,x='Income',y='MaritalStatus')
plt.show()

df.head()

pd.crosstab(df['Gender'],df['Product'])

pd.crosstab(df['MaritalStatus'],df['Product'])

df['Age'].describe()

label1 = [0,18,40,50] # 0-18 (teen), 18-40 (Adult), 4-50 (Middle age)
groups = ['Teen','Adult','Middle age']

df['Age_bins'] = pd.cut(df['Age'],label1,labels=groups)
df
df['Age_bins'].value_counts()

sns.countplot(df,x='Age_bins',hue='Product')
plt.show()

"""It is observed that **adult people** are using the treadmill most then **teens and middle aged**."""

df['Income'].describe()

labels2 = [20000,40000,70000,110000]
groups2 = ['Low','Medium','high']

df['Income_bin'] = pd.cut(df['Income'],labels2,labels=groups2)
df.head()

sns.countplot(df,x='Income_bin',hue='Product')
plt.show()

"""**Medium income** people are spending most on the fitness compared to the Low and high income people also spending most on **entry-level** and
**medium-level** treadmills. High income people are spending most on the **advanced-level **Treadmills.
"""

pd.crosstab(df['Age_bins'],df['Income_bin'])

pd.crosstab(df['Age_bins'],df['Product'])

df.head()

# Plotting
plt.figure(figsize=(6, 4))
plt.scatter(df['Age'], df['Miles'], color='blue', marker='o', label='Age vs Income')
plt.title('Scatter Plot of Age vs Miles')
plt.xlabel('Age')
plt.ylabel('Miles')
plt.legend()
plt.grid(True)
plt.show()

"""There is no correlation between the **Age** and **Miles** walked on the treadmill.

* The targeted audience for this treadmill includes both adult men and women.
* Higher-income individuals tend to invest in advanced-level treadmills.
* Adults with medium salaries form the majority of treadmill buyers.
* The age group between 20-40 shows the highest spending on this product.
* Younger adults in their 20s prefer mid-range treadmills, balancing cost and features.
* Individuals above 40 tend to invest in premium treadmills, likely for durability and advanced features.
* Price sensitivity is evident among middle-income buyers, influencing their treadmill choice.
* The spending pattern suggests a strong correlation between income level and treadmill preference.
* Marketing efforts should focus on professionals and fitness-conscious adults.
Promotions targeting the 20-40 age group can maximize sales and brand reach.
"""

